import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

export async function POST(
  req: Request,
  ctx: { params: Promise<{ id: string }> },
) {
  const { id: scenarioId } = await ctx.params;
  const scenario = await prisma.scenario.findUnique({ where: { id: scenarioId } });
  if (!scenario) return NextResponse.json({ error: "场景不存在" }, { status: 404 });

  const body = (await req.json()) as {
    name: string;
    identity?: unknown;
    behavior?: unknown;
    relationships?: unknown;
    autoGenerated?: boolean;
    modelOverrideId?: string | null;
  };
  if (!body.name) {
    return NextResponse.json({ error: "缺少 name" }, { status: 400 });
  }

  const char = await prisma.character.create({
    data: {
      scenarioId,
      name: body.name,
      identity: JSON.stringify(body.identity ?? {}),
      behavior: JSON.stringify(body.behavior ?? {}),
      relationships: JSON.stringify(body.relationships ?? {}),
      autoGenerated: body.autoGenerated ?? false,
      modelOverrideId: body.modelOverrideId ?? null,
    },
  });
  return NextResponse.json(char);
}
