import { create } from "zustand";

export type Fidelity = "strict" | "moderate" | "fiction";

export type TimeAnchorKind = "era" | "highlight";

export interface WizardCharacter {
  position: string;
  name: string;
  identity: Record<string, unknown>;
  behavior?: Record<string, unknown>;
  autoGenerated: boolean;
}

export interface WizardState {
  step: number;
  dynastyId: string | null;
  /** 年号轴 id，或大事 `evt:{highlightId}` */
  periodId: string | null;
  timeKind: TimeAnchorKind | null;
  year: number | null;
  sceneId: string | null;
  characters: WizardCharacter[];
  topicTitle: string;
  topicType: string;
  topicContext: string;
  protagonistObjective: string;
  protagonistConstraints: string[];
  fidelity: Fidelity;
  modelEndpointId: string | null;
  /** 用于 RAG 的 Embedding 端点（与 LLM 端点分离） */
  embeddingModelId: string | null;
  selectedKnowledgeIds: string[];
  /** 可选：场景归属项目（便于与史料分组同域管理） */
  projectId: string | null;
  /** 人物列表下标，保存场景后写入 scenario.protagonistCharacterId */
  protagonistCharacterIndex: number | null;
  /** 主视角玩家的额外指令（写入 protagonist JSON） */
  playableDirectives: string;
  background: string;
  setStep: (n: number) => void;
  setDynasty: (id: string | null) => void;
  setTimeEra: (eraSegmentId: string) => void;
  setTimeHighlight: (highlightId: string, anchorYear?: number | null) => void;
  clearTimeAnchor: () => void;
  setYear: (y: number | null) => void;
  setScene: (id: string | null) => void;
  setCharacters: (c: WizardCharacter[]) => void;
  updateCharacter: (index: number, patch: Partial<WizardCharacter>) => void;
  setTopic: (p: Partial<Pick<WizardState, "topicTitle" | "topicType" | "topicContext">>) => void;
  setProtagonist: (objective: string, constraints: string[]) => void;
  setFidelity: (f: Fidelity) => void;
  setModelEndpointId: (id: string | null) => void;
  setEmbeddingModelId: (id: string | null) => void;
  toggleKnowledgeSource: (id: string) => void;
  setProjectId: (id: string | null) => void;
  setProtagonistCharacterIndex: (i: number | null) => void;
  setPlayableDirectives: (s: string) => void;
  setBackground: (s: string) => void;
  reset: () => void;
}

const initial = {
  step: 1,
  dynastyId: null as string | null,
  periodId: null as string | null,
  timeKind: null as TimeAnchorKind | null,
  year: null as number | null,
  sceneId: null as string | null,
  characters: [] as WizardCharacter[],
  topicTitle: "",
  topicType: "historical",
  topicContext: "",
  protagonistObjective: "",
  protagonistConstraints: [] as string[],
  fidelity: "moderate" as Fidelity,
  modelEndpointId: null as string | null,
  embeddingModelId: null as string | null,
  selectedKnowledgeIds: [] as string[],
  projectId: null as string | null,
  protagonistCharacterIndex: null as number | null,
  playableDirectives: "",
  background: "",
};

export const useScenarioWizardStore = create<WizardState>((set) => ({
  ...initial,
  setStep: (step) => set({ step }),
  // 切换朝代时清空时间锚点；同一朝代重复 set（如时间轴「进入向导」前再写一次）不得清空已选年号/大事
  setDynasty: (dynastyId) =>
    set((state) => {
      if (dynastyId === state.dynastyId) {
        return {};
      }
      return {
        dynastyId,
        periodId: null,
        timeKind: null,
        year: null,
        selectedKnowledgeIds: [],
      };
    }),
  setTimeEra: (eraSegmentId) =>
    set({ periodId: eraSegmentId, timeKind: "era" }),
  setTimeHighlight: (highlightId, anchorYear) =>
    set((s) => ({
      periodId: `evt:${highlightId}`,
      timeKind: "highlight",
      year: s.year != null ? s.year : anchorYear ?? null,
    })),
  clearTimeAnchor: () => set({ periodId: null, timeKind: null }),
  setYear: (year) => set({ year }),
  setScene: (sceneId) => set({ sceneId }),
  setCharacters: (characters) => set({ characters }),
  updateCharacter: (index, patch) =>
    set((s) => ({
      characters: s.characters.map((c, i) =>
        i === index ? { ...c, ...patch } : c,
      ),
    })),
  setTopic: (p) => set(p),
  setProtagonist: (protagonistObjective, protagonistConstraints) =>
    set({ protagonistObjective, protagonistConstraints }),
  setFidelity: (fidelity) => set({ fidelity }),
  setModelEndpointId: (modelEndpointId) => set({ modelEndpointId }),
  setEmbeddingModelId: (embeddingModelId) => set({ embeddingModelId }),
  toggleKnowledgeSource: (id) =>
    set((s) => ({
      selectedKnowledgeIds: s.selectedKnowledgeIds.includes(id)
        ? s.selectedKnowledgeIds.filter((x) => x !== id)
        : [...s.selectedKnowledgeIds, id],
    })),
  setProjectId: (projectId) => set({ projectId }),
  setProtagonistCharacterIndex: (protagonistCharacterIndex) =>
    set({ protagonistCharacterIndex }),
  setPlayableDirectives: (playableDirectives) => set({ playableDirectives }),
  setBackground: (background) => set({ background }),
  reset: () => set(initial),
}));
