import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

export async function PUT(
  req: Request,
  ctx: { params: Promise<{ id: string }> },
) {
  const { id } = await ctx.params;
  const body = (await req.json()) as {
    name?: string;
    identity?: unknown;
    behavior?: unknown;
    relationships?: unknown;
    autoGenerated?: boolean;
    modelOverrideId?: string | null;
  };
  const data: Record<string, unknown> = {};
  if (body.name != null) data.name = body.name;
  if (body.identity !== undefined) data.identity = JSON.stringify(body.identity);
  if (body.behavior !== undefined) data.behavior = JSON.stringify(body.behavior);
  if (body.relationships !== undefined) {
    data.relationships = JSON.stringify(body.relationships);
  }
  if (body.autoGenerated !== undefined) data.autoGenerated = body.autoGenerated;
  if (body.modelOverrideId !== undefined) data.modelOverrideId = body.modelOverrideId;
  try {
    const row = await prisma.character.update({ where: { id }, data });
    return NextResponse.json(row);
  } catch {
    return NextResponse.json({ error: "未找到" }, { status: 404 });
  }
}

export async function DELETE(
  _req: Request,
  ctx: { params: Promise<{ id: string }> },
) {
  const { id } = await ctx.params;
  try {
    await prisma.character.delete({ where: { id } });
    return NextResponse.json({ ok: true });
  } catch {
    return NextResponse.json({ error: "未找到" }, { status: 404 });
  }
}
